version: '2.2'

services:
  videostream:
    container_name: videostream
    build:
      context: ./videostream
    volumes:
      - station_data:/var/azuracast/stations
    restart: always
    logging:
      options: 
        max-size: "1m"
        max-file: "5"
    environment:
      # VS_VBR: 1500k
      # VS_FPS: 24
      # VS_QUALITY: superfast
      VS_RTMP_SERVER: rtmp://a.rtmp.youtube.com/live2/g4xc-u5ew-au3z-70wj-bgr2
      # VS_FONT_FILE: /usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf
      VS_TEXT_SOURCE: /var/azuracast/stations/azuratest_radio/config/nowplaying.txt
      # VS_TEXT_SIZE: 55
      # VS_TEXT_BOX: 1
      # VS_TEXT_BOX_COLOR: black@0.5
      # VS_TEXT_BORDER_W: 20
      # VS_TEXT_X: 100
      # VS_TEXT_Y: 350
      VS_AUDIO_SOURCE: http://45.63.75.109:8000/radio.mp3
      VS_VIDEO_SOURCE: /var/azuracast/videostream/example.mp4
